### PR TITLE
Add shoulder buttons to gamepadtokey.js

### PR DESCRIPTION
**Pull request by janmonschke**
Added left and right shoulder button to gamepadtokey.js

### CODE REVIEW

**Comment by payzer** [comment]
Thank you for the pull request. 

Looks good, but could you change the button names to?

GAMEPAD_LEFT_SHOULDER (instead of GAMEPAD_SHOULDER_LEFT)
GAMEPAD_RIGHT_SHOULDER (instead of GAMEPAD_SHOULDER_RIGHT)

(also change the variable names & other places)

That's the names we use in C++ and the controller driver.

**Comment by janmonschke** [comment]
@payzer done :)

**Comment by payzer** [comment]
Thank you. Merged.

**Comment by janmonschke** [comment]
Thanks for merging @payzer !

After testing my UWP app with this library I realized though that I do not need it in the end since all the gamepad's buttons are already exposed on the Xbox with a `keydown` event listener. Do you know if there is a documentation for the available keys and keycodes?

**Comment by payzer** [comment]
Thank you for the feedback. I've added a page with the information you were interested in:

https://github.com/Microsoft/TVHelpers/wiki/Gamepad-button-enumeration-for-UWPs

**Pull request merged**
